advanced:
  gemini:
    convergence_threshold: 0.001
    max_iterations: 50
  matplotlib:
    available_fallback: "\u26A0\uFE0F  Matplotlib no disponible. Gr\xE1ficos deshabilitados."
  normalization:
    reward_normalize: true
    state_normalize: true
  optuna:
    n_trials: 100
    timeout: 3600
  time_parameter: 1.0
app:
  banner:
    char: '='
    width: 60
  title: HNAF Training and Evaluation GUI
  window:
    height: 900
    width: 1400
debug:
  log_evaluation: true
  log_level: INFO
  log_training_progress: true
  print_evaluation_grid: true
  print_function_loading: true
  print_matrices: true
  verbose: true
defaults:
  coordinates:
    x0: 1
    y0: 1
  matrices:
    A1:
    - - 1
      - 50
    - - -1
      - 1
    A2:
    - - 1
      - -1
    - - 50
      - 1
  reward_function: np.linalg.norm([x, y])
  reward_optimization: minimizar
initialization:
  network:
    bias_constant: 0.0
    diagonal_offset: 0.1
    l_scale: 0.1
    mu_scale: 0.1
    xavier_gain_general: 1.0
    xavier_gain_l_head: 0.1
  seeds:
    numpy_seed: 42
    torch_seed: 42
interface:
  checkboxes:
    reward_normalize: false
    reward_shaping: false
    show_loss: true
    show_precision: true
    show_rewards: true
    use_custom_functions: false
    use_gemini_optimization: false
  status_messages:
    initializing: Iniciando...
    no_training: No iniciado
    optimization_inactive: "Optimizaci\xF3n: Inactiva"
    optuna_inactive: "Optimizaci\xF3n Optuna: Inactiva"
network:
  defaults:
    action_dim: 2
    hidden_dim: 256
    num_layers: 3
    num_modes: 2
    state_dim: 2
  ranges:
    action_dim:
    - 1
    - 10
    hidden_dim:
    - 16
    - 256
    hidden_dim_increment: 16
    num_layers:
    - 2
    - 5
    num_modes:
    - 1
    - 5
    state_dim:
    - 1
    - 10
numerical:
  state_limits:
    max: 5.0
    min: -5.0
  tolerances:
    comparison_normal: 0.001
    comparison_strict: 1.0e-10
    convergence_tolerance: 1.0e-10
    diagonal_clamp_min: 1.0e-06
    division_epsilon: 1.0e-08
    matrix_clamp_l:
    - -3
    - 3
    matrix_clamp_off_diag:
    - -1
    - 1
    priority_epsilon: 1.0e-06
optuna_optimization:
  backup_file: /Users/edenrochman/Documents/Offline_projects/HNAF Jose/config.yaml.backup_pre_optuna
  best_score: 7.884716125656723
  last_update: '2025-08-03 10:29:06'
  optimized_params:
  - hidden_dim
  - num_layers
  - lr
  - batch_size
  - initial_epsilon
  - final_epsilon
  - max_steps
  - buffer_capacity
  - alpha
  - beta
  - tau
  - gamma
  total_trials: 0
profiles:
  beginner:
    description: "Configuraci\xF3n b\xE1sica para principiantes"
    network:
      hidden_dim: 32
      num_layers: 2
    training:
      learning_rate: 0.001
      num_episodes: 500
  expert:
    description: "Configuraci\xF3n avanzada para experimentaci\xF3n"
    network:
      hidden_dim: 128
      num_layers: 4
    training:
      learning_rate: 1.0e-05
      num_episodes: 2000
  intermediate:
    description: "Configuraci\xF3n balanceada"
    network:
      hidden_dim: 64
      num_layers: 3
    training:
      learning_rate: 0.0001
      num_episodes: 1000
  research:
    description: "Configuraci\xF3n para investigaci\xF3n intensiva"
    network:
      hidden_dim: 256
      num_layers: 5
    training:
      learning_rate: 1.0e-06
      num_episodes: 5000
reward_shaping:
  coefficients:
    approach_bonus: 0.05
    distance_penalty: 0.1
    oscillation_penalty: 0.05
    suboptimal_penalty: 0.1
    success_bonus: 1.0
  enabled: false
  mode_aware:
    correct_mode_multiplier: 0.1
    incorrect_mode_multiplier: 7.5
  state_initialization:
    min_range: -0.5
    max_range: 0.5
    convergence_threshold: 0.01
training:
  defaults:
    alpha: 0.5
    batch_size: 64
    beta: 0.3
    buffer_capacity: 20000
    final_epsilon: 0.05
    gamma: 0.999
    initial_epsilon: 0.6
    learning_rate: 0.012075241256926888
    max_steps: 200
    num_episodes: 1000
    supervised_episodes: 50
    tau: 0.005
  evaluation:
    grid_size: 50
    grid_size_display: 100
    interval: 50
    num_episodes: 10
  ranges:
    alpha:
    - 0.0
    - 1.0
    batch_size:
    - 8
    - 128
    batch_size_increment: 8
    beta:
    - 0.0
    - 1.0
    buffer_capacity:
    - 1000
    - 50000
    buffer_increment: 1000
    episodes_increment: 100
    epsilon_increment: 0.05
    final_epsilon:
    - 0.01
    - 0.2
    final_epsilon_increment: 0.01
    gamma:
    - 0.8
    - 0.999
    gamma_increment: 0.001
    initial_epsilon:
    - 0.1
    - 1.0
    learning_rate:
    - 0.0001
    - 0.1
    learning_rate_increment: 0.0001
    max_steps:
    - 10
    - 200
    num_episodes:
    - 100
    - 5000
    priority_increment: 0.1
    supervised_episodes:
    - 0
    - 500
    supervised_increment: 50
    tau:
    - 0.0001
    - 0.01
    tau_increment: 0.0001
